service:
  port: 0

health:
  port: 0

instance:
  id: 5 # change this from infrastructure to be the ID of the service within its cluster e.g., 0, 1, or 2 in a cluster with 3 nodes.
  group:
    name: example-write-endpoint # do not change this from infrastructure
    max:
      size: 256 # change this from infrastructure to be the maximum number of instances in the cluster e.g., 256 in a cluster with 256 maximum nodes.