openapi: 3.1.0
#openapi: 3.0.1
info:
  title: Example Write Endpoint Service API
  description: Accepts commands to register a user.
  version: "1.0"
paths:
  /commands/register-user/1:
    post:
      summary: Submits a register user V1 command to register a new user.
      parameters:
        - in: header
          name: Accept
          description: The media type accepted by the client.
          required: false
          schema:
            type: string
      requestBody:
        description: Details of the new user to be registered.
        content:
          application/json:
            schema:
              $ref: '/api/schemas/json/IssueCardCommand.json'
            example: { "email": { "address": "bruce@waynecorp.com" } }
        required: true
      responses:
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/UnexpectedError'
        502:
          $ref: '#/components/responses/UnavailableServer'
components:
  headers:
    location:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    date:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    connection:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    transferEncoding:
      schema:
        type: string
        minLength: 1
      required: true
      description: Transfer encoding
    contentType:
      schema:
        type: string
        minLength: 1
      required: true
      description: Content type
    contentLength:
      schema:
        type: string
        minLength: 1
      required: true
      description: Content length
  responses:
    Accepted:
      description: The command was accepted.
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
        date:
          $ref: '#/components/headers/date'
        connection:
          $ref: '#/components/headers/connection'
        transfer-encoding:
          $ref: '#/components/headers/transferEncoding'
    BadRequest:
      description: The request could not be understood e.g., headers, query parameters or request body are malformed.
      content:
        application/json:
          schema:
            $ref: '/api/schemas/json/ErrorsList.json'
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
        date:
          $ref: '#/components/headers/date'
        connection:
          $ref: '#/components/headers/connection'
        transfer-encoding:
          $ref: '#/components/headers/transferEncoding'
    UnprocessableEntity:
      description: The request body violated domain constraints.
      content:
        application/json:
          schema:
            $ref: '/api/schemas/json/ErrorsList.json'
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
        date:
          $ref: '#/components/headers/date'
        connection:
          $ref: '#/components/headers/connection'
        transfer-encoding:
          $ref: '#/components/headers/transferEncoding'
    UnavailableServer:
      description: A dependent service is not responding.
      content:
        application/json:
          schema:
            $ref: '/api/schemas/json/ErrorsList.json'
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
        date:
          $ref: '#/components/headers/date'
        connection:
          $ref: '#/components/headers/connection'
        transfer-encoding:
          $ref: '#/components/headers/transferEncoding'
    UnexpectedError:
      description: Something went wrong unexpectedly.
      content:
        application/json:
          schema:
            $ref: '/api/schemas/json/ErrorsList.json'
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
        date:
          $ref: '#/components/headers/date'
        connection:
          $ref: '#/components/headers/connection'
        transfer-encoding:
          $ref: '#/components/headers/transferEncoding'