openapi: 3.1.0
info:
  title: Example Command Endpoint Service API
  description: Accepts commands to register a user.
  version: "1.0"
paths:
  /commands/register-user/v1:
    post:
      operationId: registerUserV1
      summary: Submits a register user V1 command to register a new user.
      parameters:
        - $ref: '#/components/parameters/invocationContext'
        - $ref: '#/components/parameters/accept'
        - $ref: '#/components/parameters/contentLength'
      requestBody:
        description: Details of the new user to be registered.
        content:
          application/json:
            schema:
              $ref: '/api/schemas/json/user/registration/RegisterUserCommandV1.json'
            example: { "email": { "address": "bruce@waynecorp.com" } }
        required: true
      responses:
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "415":
          $ref: '#/components/responses/UnsupportedMediaType'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/UnexpectedError'
        502:
          $ref: '#/components/responses/BadGateway'
components:
  parameters:
    invocationContext:
      name: x-acme-invocation-context
      in: header
      description: Invocation context from the API gateway
      required: true
      style: simple
      explode: false
      schema:
        $ref: '/correlation/context/InvocationContext.json'
        # TODO Move to a file
        example: { "trace": { "originating": { "created-at": "2024-04-05T14:19:40.997603Z","id": { "type": "ksuid","value": "2egWcntU0AGcyUbl3u4shVkY9SD" } },"parent": { "created-at": "2024-04-05T14:19:41.997603Z","id": { "type": "ksuid","value": "2egWcntU0AGcyUbl3u4shVkY9SE" } },"invocation": { "created-at": "2024-04-05T14:19:43.997603Z","id": { "type": "ksuid","value": "2egWcntU0AGcyUbl3u4shVkY9SF" } },"external": { "action-id": { "type": "string","value": "01HTQA2D06XGT2HF686A1VS070" },"invocation-id": { "type": "string","value": "01HTQA2D05QDJHM9XH512GR1CE" } } },"access": { "authorization": { "roles": { "values": [ ] } },"origin": { "client-info": { "agent": { "name": "Apache-HttpAsyncClient","version": { "patch": 1,"major": 5,"minor": 2,"type": "semantic" },"class-name": "Special" },"layout-engine": { "name": "AppleWebKit","version": { "patch": 25,"major": 800,"minor": 6,"type": "semantic" },"class-name": "WebKit" },"operating-system": { "name": "Android (Upside Down Cake)","version": { "type": "simple","value": "14" },"class-name": "Android" },"device": { "name": "Pixel 8","brand": "Google","class-name": "Mobile" } },"ip-address": "127.0.0.1" },"scope": { "container-stack": [ { "id": { "type": "ksuid","value": "2egWcntU0AGcyUbl3u4shVkY9SB" } },{ "id": { "type": "ksuid","value": "2egWcntU0AGcyUbl3u4shVkY9SC" } } ] },"type": "unauthenticated" },"toggles": { "values": [ ] } }
    contentLength:
      name: content-length
      in: header
      description: Length of the request body
      required: true
      style: simple
      explode: false
      schema:
        minLength: 1
        type: string
    accept:
      name: Accept
      in: header
      description: The media type accepted by the client.
      required: false
      schema:
        type: string
  headers:
    location:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    date:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    connection:
      schema:
        type: string
        minLength: 1
      required: true
      description: Location
    transferEncoding:
      schema:
        type: string
        minLength: 1
      required: true
      description: Transfer encoding
    contentType:
      schema:
        type: string
        minLength: 1
      required: true
      description: Content type
    contentLength:
      schema:
        type: string
        minLength: 1
      required: true
      description: Content length
  responses:
    Accepted:
      description: The command was accepted.
      content:
        application/json:
          schema:
            $ref: '/api/schemas/json/user/registration/RegisterUserCommandV1AcceptedResult.json'
          example: { "user": { "id": "01H8HBDMX0S2EGDTR7WAGK0SC7" } }
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'
    BadRequest:
      description: The request could not be understood e.g., headers, query parameters or request body are malformed.
    UnsupportedMediaType:
      description: The content type in the request body is not supported.
    UnprocessableEntity:
      description: The request body violated domain constraints.
    BadGateway:
      description: A dependent service is not responding.
    UnexpectedError:
      description: Something went wrong unexpectedly.
      content:
        text/plain:
          schema:
            type: string
          example: "Something went wrong on the server"
      headers:
        content-type:
          $ref: '#/components/headers/contentType'
        content-length:
          $ref: '#/components/headers/contentLength'